### ISSUE TITLE
Length conversion looks wrong

### ISSUE THREAD

**Issue by evilpie** [guest271314/native-messaging-quickjs#1]
https://github.com/guest271314/native-messaaging-quickjs/blob/5e77021e5120865cc647e3197dc856abb16db4d9/nm_qjs.js#L11

This Uint32Array only has one element so the reduce isn't doing anything. I think you could replace the whole code with:
```js
const header = new Uint32Array(1);
std.in.read(header.buffer, 0, header.byteLength);
// https://stackoverflow.com/a/26140545
const length = header[0];
```

**Comment by guest271314** [comment]
Are you sure? Native Messaging protocol states the 

What happens

> if the length is greater than 255.

https://stackoverflow.com/a/26140545 ?

https://github.com/simov/native-messaging/blob/master/protocol.js#L12 does only use 

```
    var msgLen = input.readUInt32LE(0)
```

**Comment by guest271314** [comment]
@evilpie I can't determine a difference via testing. PR's welcome.
